// Pure, dependency-free helpers for the idea pipeline.
// Kept free of `fs`/SvelteKit imports so they are trivially unit-testable.

export type Stage = 'prospects' | 'validated' | 'specs';

/**
 * Derive a human-readable title for an idea.
 * Prefers the first markdown H1 in the content, then falls back to a
 * de-slugified version of the filename.
 */
export function extractTitle(filename: string, content: string): string {
    const titleMatch = content.match(/^#\s+(.+)$/m);
    if (titleMatch) return titleMatch[1].trim();
    return filename.replace(/\.md$/, '').replace(/-\d{13}$/, '').replace(/-/g, ' ').trim();
}

/**
 * Files generated by the app embed their creation time as a 13-digit
 * millisecond timestamp suffix (e.g. `my-idea-1780822753436.md`).
 * Use it when present so ordering survives file copies; otherwise fall back.
 */
export function extractTimestamp(filename: string, fallback: number): number {
    const match = filename.match(/-(\d{13})\.md$/);
    return match ? parseInt(match[1], 10) : fallback;
}

/**
 * Turn a free-text niche into a safe, lowercase filename slug (no extension,
 * no timestamp). Callers append `-${Date.now()}.md`.
 */
export function slugify(niche: string): string {
    return niche
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '');
}

/** Build the on-disk filename for a freshly generated prospect. */
export function ideaFilename(niche: string, now: number = Date.now()): string {
    return `${slugify(niche)}-${now}.md`;
}
